version: '3'
services:
  microservice1:
    build:
      context: ./microservice1
    ports:
      - "5001:5001"
    volumes:
      - ./microservice1:/app
  microservice2:
    build:
      context: ./microservice2
    ports:
      - "5002:5002"
    volumes:
      - ./microservice2:/app
    depends_on:
      - microservice1
